<?php

$siswa = ["Andrian", "Ardika", "Dudi", "Hendri", "Ilyas", "Napis", "Sandi", "Surya", "Kiki", "Sidik"];
$jenis_kelamin = ["Laki - Laki", "Perempuan"];
$hobi = ["Membaca", "Main Basket", "Main Bola", "Ngepush", "Menari",];

foreach($siswa as $data){
    echo "$data <br>";
}
echo "<br>";
echo $siswa[0];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[1];
echo "<br><br>";
echo $siswa[1];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[0];
echo "<br><br>";
echo $siswa[2];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[4];
echo "<br><br>";
echo $siswa[3];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[3];
echo "<br><br>";
echo $siswa[4];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[4];
echo "<br><br>";
echo $siswa[5];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[2];
echo "<br><br>";
echo $siswa[6];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[0];
echo "<br><br>";
echo $siswa[7];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[3];
echo "<br><br>"; 
echo $siswa[8];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[4];
echo "<br><br>";
echo $siswa[9];
echo "_";
echo $jenis_kelamin[0];
echo "_";
echo $hobi[2];
echo "<br><br>";
?>